name: Terraform

on:
  push:
    branches:
      - main
  pull_request:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.7.4'  # Specify your Terraform version

      - name: Terraform Init
        run: terraform init -chdir=./infra

      - name: Terraform Format Check
        run: terraform fmt -check -chdir=./infra

      - name: Terraform Validate
        run: terraform validate -chdir=./infra

      - name: Terraform Plan
        if: github.event_name == 'pull_request'
        run: terraform plan -no-color -var="alarm_email=${{ secrets.ALARM_EMAIL }}" -chdir=./infra
        continue-on-error: true

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve -var="alarm_email=${{ secrets.ALARM_EMAIL }}" -chdir=./infra